services:
  mongodb:
    image: mongo:latest
    container_name: music-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
  redis:
    image: redis:alpine
    container_name: music-redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
